# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 21f34250679444cc93682e994ed351126ba1c169

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: mail.tigra.hu
    port: 25
    username: toth.gabor@tigra.hu
    password: *
    protocol: smtp
    tls: false
    auth: true
    from: toth.gabor@tigra.hu


swagger:
    title: first API
    description: first applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
